### ISSUE TITLE
No profiles listed...

### ISSUE THREAD

**Issue by jasmines** [noam09/ulauncher-remmina#6]
I have several profiles in Remmina, but none of them is listed in Ulauncher extension.
I'm on Ubuntu 19.04 Plasma DE.

**Comment by noam09** [comment]
Hi @jasmines, in which directory are your profiles stored? Can you look over a debug log to see if any errors pop up for this extension?

`pkill ulauncher && ulauncher -v --dev`

**Comment by noam09** [comment]
Reopen if needed

**Comment by rabin-io** [comment]
Hi after moving from ver 4 to ver 5 I have the same problem, and ulauncher hang on "Loading..."
this is the ST that I see in the terminal

```
com.github.noam09.ulauncher-remmina | 2019-10-31 21:54:41,448 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event KeywordQueryEvent
DEBUG:__main__:Remmina profiles path: /home/rabin/.local/share/remmina
com.github.noam09.ulauncher-remmina | 2019-10-31 21:54:41,448 | DEBUG | __main__: on_event() | Remmina profiles path: /home/rabin/.local/share/remmina
DEBUG:ulauncher.api.client.Client:Send message
com.github.noam09.ulauncher-remmina | 2019-10-31 21:54:41,458 | DEBUG | ulauncher.api.client.Client: send() | Send message
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ulauncher/api/client/Client.py", line 54, in on_message
    self.extension.trigger_event(event)
  File "/usr/lib/python3.7/site-packages/ulauncher/api/client/Extension.py", line 55, in trigger_event
    self._client.send(Response(event, action))
  File "/usr/lib/python3.7/site-packages/ulauncher/api/client/Client.py", line 85, in send
    self.ws.send(pickle.dumps(response))
  File "/usr/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/usr/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/usr/lib/python3.7/site-packages/websocket/_core.py", line 269, in send_frame
    data = frame.format()
  File "/usr/lib/python3.7/site-packages/websocket/_abnf.py", line 242, in format
    return frame_header + self._get_masked(mask_key)
  File "/usr/lib/python3.7/site-packages/websocket/_abnf.py", line 245, in _get_masked
    s = ABNF.mask(mask_key, self.data)
  File "/usr/lib/python3.7/site-packages/websocket/_abnf.py", line 276, in mask
    a = numpy.frombuffer(data, dtype="uint32")
AttributeError: module 'numpy' has no attribute 'frombuffer'
```

**Comment by noam09** [comment]
Hi @rabin-io, thanks for sharing how this was resolved. It's odd though, the error seems to originate from the `websocket` module, which is used by UL for all extensions. Did this happen with other extensions as well or just this one?

**Comment by rabin-io** [comment]
Can't say for sure, but I don't remember having any problem with any other plugin.
